cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/',include('orders.urls', namespace='orders')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^', include('shop.urls', namespace='shop')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',views.order_create,name='order_create'),
    url(r'^complete/$',views.order_complete,name='order_complete'),
    url(r'^admin/order/(?P<order_id>\d+)/$',views.admin_order_detail,name='admin_order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$',views.admin_order_pdf, name='admin_order_pdf'),

    url(r'^create_ajax/$', views.OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    url(r'^checkout/$', views.OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    url(r'^validation/$', views.OrderImpAjaxView.as_view(), name='order_validation'),
]

orders/models.py
from django.db import models
from shop.models import Product

from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon

from .iamport import validation_prepare, get_transaction
import time
import random
import hashlib
from django.db.models.signals import post_save
# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    coupon = models.ForeignKey(Coupon,
                               related_name='orders',
                               null=True,
                               blank=True)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])


    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_product(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_total_discount(self):
        return self.get_total_product()*(self.discount / Decimal('100'))

    def get_total_cost(self):
        total_cost = self.get_total_product()
        total_discount = self.get_total_discount()
        return total_cost - total_discount

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return '{}'.format(self.id)
    def get_cost(self):
        return self.price * self.quantity


class OrderTransactionManager(models.Manager):
    # 새로운 트랜젝션 생성
    def create_new(self, order, amount, success=None, transaction_status=None):
        if not order:
            raise ValueError("주문이 확인되지 않습니다.")

        short_hash = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:2]
        time_hash = hashlib.sha1(str(int(time.time())).encode('utf-8')).hexdigest()[-3:]
        base = str(order.email).split("@")[0]
        key = hashlib.sha1((short_hash + time_hash + base).encode('utf-8')).hexdigest()[:10]
        merchant_order_id = "%s" % (key)

        # 아임포트 결제 사전 검증 단계
        validation_prepare(merchant_order_id, amount)

        # 트랜젝션 저장
        new_trans = self.model(
            order=order,
            merchant_order_id=merchant_order_id,
            amount=amount
        )

        if success is not None:
            new_trans.success = success
            new_trans.transaction_status = transaction_status

        new_trans.save(using=self._db)
        return new_trans.merchant_order_id

    def validation_trans(self, merchant_order_id):
        result = get_transaction(merchant_order_id)
        if result['status'] == 'paid':
            return result
        else:
            return None

class OrderTransaction(models.Model):
    order = models.ForeignKey(Order)
    merchant_order_id = models.CharField(max_length=120, null=True, blank=True)
    transaction_id = models.CharField(max_length=120, null=True, blank=True)
    amount = models.PositiveIntegerField(default=0)
    transaction_status = models.CharField(max_length=220, null=True, blank=True)
    type = models.CharField(max_length=120,blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    objects = OrderTransactionManager()

    def __str__(self):
        return str(self.order.id)

    class Meta:
        ordering = ['-created']

def new_order_trans_validation(sender, instance, created, *args, **kwargs):
    if instance.transaction_id:
        # 거래 후 아임포트에서 넘긴 결과
        v_trans = OrderTransaction.objects.validation_trans(
            merchant_order_id=instance.merchant_order_id
        )

        res_merchant_id = v_trans['merchant_order_id']
        res_imp_id = v_trans['imp_id']
        res_amount = v_trans['amount']

        # 데이터베이스에 실제 결제된 정보가 있는지 체크
        r_trans = OrderTransaction.objects.filter(
            merchant_order_id=res_merchant_id,
            transaction_id=res_imp_id,
            amount=res_amount
        ).exists()

        if not v_trans or not r_trans:
            raise ValueError('비정상적인 거래입니다.')

post_save.connect(new_order_trans_validation, sender=OrderTransaction)

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','email','address','postal_code','city']

orders/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from .models import *
from cart.cart import Cart
from .forms import OrderCreateForm

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint

from django.views.generic.base import View
from django.http import JsonResponse
from .models import *
# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
            cart.clear()

            return render(request,'orders/order/created.html',{'order':order})
    else:
        form = OrderCreateForm()
    return render(request,'orders/order/create.html',{'cart':cart,'form':form})

def order_complete(request):
    order_id = request.GET.get('order_id')
    order = Order.objects.get(id=order_id)
    return render(request,'orders/order/created.html',{'order':order})

@staff_member_required
def admin_order_detail(request,order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'admin/orders/order/detail.html',{'order':order})

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',{'order':order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=order_{}.pdf'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.STATICFILES_DIRS[0]+'/css/pdf.css')])
    return response

class OrderCreateAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated":False}, status=403)

        cart = Cart(request)
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            data = {
                "order_id": order.id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)

class OrderCheckoutAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated":False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        amount = request.POST.get('amount')


        try:
            merchant_order_id = OrderTransaction.objects.create_new(
                order=order,
                amount=amount
            )
        except:
            merchant_order_id = None

        if merchant_order_id is not None:
            data = {
                "works": True,
                "merchant_id": merchant_order_id
            }
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


class OrderImpAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated":False}, status=403)

        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        merchant_id = request.POST.get('merchant_id')
        imp_id = request.POST.get('imp_id')
        amount = request.POST.get('amount')

        try:
            trans = OrderTransaction.objects.get(
                order=order,
                merchant_order_id=merchant_id,
                amount=amount
            )
        except:
            trans = None

        if trans is not None:
            trans.transaction_id = imp_id
            trans.success = True
            trans.save()
            order.paid = True
            order.save()

            data = {
                "works": True
            }

            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)

orders/templates/orders/order/create.html
{% extends 'base.html' %}
{% block title %}
Checkout
{% endblock %}
{% block script %}
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.1.js"></script>
<script type="text/javascript">
    jQuery.fn.serializeObject = function() {
      var arrayData, objectData;
      arrayData = this.serializeArray();
      objectData = {};

      $.each(arrayData, function() {
        var value;

        if (this.value != null) {
          value = this.value;
        } else {
          value = '';
        }

        if (objectData[this.name] != null) {
          if (!objectData[this.name].push) {
            objectData[this.name] = [objectData[this.name]];
          }

          objectData[this.name].push(value);
        } else {
          objectData[this.name] = value;
        }
      });

      return objectData;
    };
    $(function () {
        var IMP = window.IMP;
        // 가맹점 코드
        IMP.init('imp11383217');

        $('.order-form').on('submit', function (e) {
            var amount = parseFloat($('.order-form input[name="amount"]').val().replace(',', ''));
            var type = $('.order-form input[name="type"]:checked').val();
            var order_id = AjaxCreateOrder(e);
            if (order_id == false) {
                alert('주문 생성 실패\n다시 시도해주세요.');
                return false;
            }
            var merchant_id = AjaxStoreTransaction(e, order_id, amount, type);

            if (merchant_id !== '') {
                IMP.request_pay({
                    merchant_uid: merchant_id,
                    name: 'E-Shop product',
                    buyer_name:$('input[name="first_name"]').val()+" "+$('input[name="last_name"]').val(),
                    buyer_email:$('input[name="email"]').val(),
                    amount: amount
                }, function (rsp) {
                    if (rsp.success) {
                        var msg = '결제가 완료되었습니다.';
                        msg += '고유ID : ' + rsp.imp_uid;
                        msg += '상점 거래ID : ' + rsp.merchant_uid;
                        msg += '결제 금액 : ' + rsp.paid_amount;
                        msg += '카드 승인번호 : ' + rsp.apply_num;
                        ImpTransaction(e, order_id, rsp.merchant_uid, rsp.imp_uid, rsp.paid_amount);
                    } else {
                        var msg = '결제에 실패하였습니다.';
                        msg += '에러내용 : ' + rsp.error_msg;
                        console.log(msg);
                    }
                });
            }
            return false;
        });
    });

    function AjaxCreateOrder(e) {
        e.preventDefault();
        var order_id = '';
        var request = $.ajax({
            method: "POST",
            url: '{% url "orders:order_create_ajax" %}',
            async: false,
            data: $('.order-form').serializeObject()
        });
        request.done(function (data) {
            if (data.order_id) {
                order_id = data.order_id;
            }
        });
        request.fail(function (jqXHR, textStatus) {
            if (jqXHR.status == 404) {
                alert("페이지가 존재하지 않습니다.");
            } else if (jqXHR.status == 403) {
                alert("로그인 해주세요.");
            } else {
                alert("문제가 발생했습니다. 다시 시도해주세요.");
            }
        });
        return order_id;
    }

    function AjaxStoreTransaction(e, order_id, amount, type) {
        e.preventDefault();
        var merchant_id = '';
        var request = $.ajax({
            method: "POST",
            url: '{% url "orders:order_checkout" %}',
            async: false,
            data: {
                order_id : order_id,
                amount: amount,
                type: type,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
        request.done(function (data) {
            if (data.works) {
                merchant_id = data.merchant_id;
            }
        });
        request.fail(function (jqXHR, textStatus) {
            if (jqXHR.status == 404) {
                alert("페이지가 존재하지 않습니다.");
            } else if (jqXHR.status == 403) {
                alert("로그인 해주세요.");
            } else {
                alert("문제가 발생했습니다. 다시 시도해주세요.");
            }
        });
        return merchant_id;
    }

    function ImpTransaction(e, order_id,merchant_id, imp_id, amount) {
        e.preventDefault();
        var request = $.ajax({
            method: "POST",
            url: '{% url "orders:order_validation" %}',
            async: false,
            data: {
                order_id:order_id,
                merchant_id: merchant_id,
                imp_id: imp_id,
                amount: amount,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
        request.done(function (data) {
            if (data.works) {
                $(location).attr('href', location.origin+'{% url "orders:order_complete" %}?order_id='+order_id)
            }
        });
        request.fail(function (jqXHR, textStatus) {
            if (jqXHR.status == 404) {
                alert("페이지가 존재하지 않습니다.");
            } else if (jqXHR.status == 403) {
                alert("로그인 해주세요.");
            } else {
                alert("문제가 발생했습니다. 다시 시도해주세요.");
            }
        });
    }
</script>
{% endblock %}

{% block content %}
    <h1>Checkout</h1>

    <div class="order-info">
        <h3>Your Order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{item.quantity}}x {{item.product.name}}
                    <span>{{item.total_price}}</span>
                </li>
            {% endfor %}
            {% if cart.coupon %}
                <li>

                        "{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% off)

                    <span>- ${{ cart.get_discount|floatformat:"2" }}</span>
                </li>
            {% endif %}
        </ul>
        <p>Total: {{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{form.as_p}}
        {% csrf_token %}
        <input type="hidden" name="pre_order_id" value="0">
        <input type="hidden" name="amount" value="{{ cart.get_total_price_after_discount|floatformat:"2" }}">
        <p><input type="submit" value="Place Order"></p>
    </form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'base.html' %}
{% block title %}
    Order Created!
{% endblock %}

{% block content %}
    <h1>Thank you!</h1>
    <p>Your order has been successfully completed.
    Your order number is <strong>{{order.id}}</strong>
    </p>
{% endblock %}

orders/templates/orders/order/pdf.html
<html>
<body>
    <h1>My Shop</h1>
    <p>
        Invoice nr. {{ order.id }}</br>
        <span class="secondary">{{ order.created|date:"M d, Y" }}</span>
    </p>

    <h3>Bill to</h3>
    <p>
        {{ order.first_name }} {{ order.last_name }}<br>
        {{ order.email }}<br>
        {{ order.address }}<br>
        {{ order.postal_code }}, {{ order.city }}
    </p>

    <h3>Items bought</h3>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Cost</th>
            </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle "1" "2" %}">
                <td>{{ item.product.name }}</td>
                <td class="num">{{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">{{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        {% if order.coupon %}
                    <tr>
                        <td colspan="3">"{{ order.coupon.code }}" coupon ({{ order.discount }}% off)</td>
                        <td class="num">-{{ order.get_total_discount }}</td>
                    </tr>
                {% endif %}
            <tr class="total">
                <td colspan="3">Total</td>
                <td class="num">{{ order.get_total_cost }}</td>
            </tr>
        </tbody>
    </table>

    <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
        {% if order.paid %}Paid{% else %}Pending payment{% endif %}
    </span>
</body>
</html>